Esri/solutions-geoprocessing-toolbox

README.md, data_management/README.md, data_management/test/test_build_elevation/TestUtilities.py, data_management/test/test_coordinate_and_conversion/TestUtilities.py, data_management/test/test_geonames_tools/TestUtilities.py, data_management/test/test_imagery_tools/TestUtilities.py, data_management/test/test_network_data_prep/TestUtilities.py, data_management/test/test_patrol_data_capture/TestUtilities.py, data_management/test/test_publishable_tasks/TestUtilities.py, data_management/test/test_scanned_map_tools/TestUtilities.py, data_management/test/test_topographic_tools/TestUtilities.py, operational_graphics/test/test_range_cards/TestUtilities.py, suitability/test/test_maot/TestUtilities.py, suitability/test/test_path_slope/TestUtilities.py, visibility/test/test_viz_and_range/TestUtilities.py, visibility/toolboxes/scripts/TowerRangeFan.py, visibility/toolboxes/scripts/TowersLOS.py
Test scripts are updated for toolbox split and are now pointing to the 10.3 toolboxes.
Changes to README.MD for the Coordinate and Conversion tools from Position Analysis.
Some trial fixes for TowerLOS.py and TowerRangeFan.py... however there are remaining defects in GP that could still cause some problems.
=> Updates for tests and CnC doc

visibility/toolboxes/scripts/TowersLOS.py
Fixes for #59 arcpy.mp changes in TowersLOS.py
=> Fixes for #59 arcpy.mp changes in TowersLOS.py

README.md
=> Updates to main README.MD

suitability/README.md
Updates for MAoT in README and toolbox
=> Updates for MAoT in README and toolbox

data_management/toolboxes/scripts/ImportEnemySightingsXML.py, data_management/toolboxes/scripts/ImportPatrolRptXML.py
Patrol Data Capture changes from testing:
Removed unnecessary './/' that Pro was doing bad things to when
packaging (it was expanding this Namespace as a path/folder).
Made tabs/spaces consistent + added more meaningful exception while I
was at it.
=> Patrol Data Capture - Pro Workaround + Spaces2Tabs

suitability/toolboxes/scripts/RasterOffRoad.py, visibility/toolboxes/scripts/spa.py
Updated RasterOffRoad.py for SA errors saving to FGDB, saving to TIFF
instead.
Also some minor script description changes for spa.py
=> Updated RasterOffRoad.py for SA errors saving to FGDB

suitability/toolboxes/scripts/Concealment.py
Update Concealment to use Spatial Reference option instead of Web
Mercator
=> Update Concealment to use Spatial Reference option

operational_graphics/toolboxes/scripts/NumberFeatures.py
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/189
=> Fixes and updates to the number features tool

suitability/toolboxes/scripts/RasterOffRoad.py
=> Fixed issue #69

.gitmodules, README.md, visibility/toolboxes/scripts/RangeFan.py
A few fixes and added mdcs-py submodule for data_management.
=> A few fixes and added mdcs-py submodule for data_management

visibility/toolboxes/scripts/RLOS.py, visibility/toolboxes/scripts/TowerLOS.py, visibility/toolboxes/scripts/TowersLOS.py
=> Updates for Extent properties

capability/test/test_poo_tools/TemplateConfigTest.py, capability/test/test_poo_tools/TestUtilities.py, suitability/toolboxes/scripts/GenerateIntermediateLayers.py
Some updates for code guidelines and fix for MAoT
=> Some updates for code guidelines and fixe for MAoT

suitability/toolboxes/scripts/GenerateIntermediateLayers.py, suitability/toolboxes/scripts/GenerateIntermediateLayersLinearObstacles.py
Fixed Feature Dataset name for
GenerateIntermediateLayersLinearObstacles.py
Performance update for GenerateIntermediateLayers.py
=> Fix for MAoT

build.xml, visibility/test/build.xml, visibility/test/test_sun_position/TemplateConfigTest.py, visibility/test/test_sun_position/TestSunPositionAndHillshade.py, visibility/test/test_sun_position/TestUtilities.py, visibility/test/test_sun_position/build.xml
Added tests for Sun Position Analysis Tools_10.3 for issue #81
=> Added tests for Sun Position Analysis Tools_10.3 for issue #81

suitability/test/test_maot/TestModelLocalPeaks.py, suitability/test/test_maot/TestUtilities.py
=> Fixes for #237

visibility/test/test_sun_position/SunPositionAndHillshadeUnitTest.py, visibility/test/test_sun_position/TemplateConfigTest.py, visibility/test/test_sun_position/TestSunPositionAndHillshade.py, visibility/test/test_sun_position/build.xml
Re-worked Sun Position Analysis Test to use Python's unittest module. Also introduced ability to add logging to a file.
=> Sun Position Analysis Test: unittest and logging

visibility/test/test_sun_position/SunPositionAndHillshadeUnitTest.py, visibility/test/test_sun_position/TestSunPositionAndHillshade.py, visibility/test/test_sun_position/UnitTestUtilities.py, visibility/test/test_sun_position/build.xml
Displaying system configuration info in the log file header.
=> Log file header

utils/test/TestRunner.py, utils/test/TestUtilities.py, utils/test/visibility_tests/SunPositionAnalysisToolsTestSuite.py, utils/test/visibility_tests/SunPositionAndHillshadeTestCase.py
Ran SunPosition Suite from TestRunner. Created pro and desktop test
functions.
=> SunPosSuite

utils/test/Configuration.py, utils/test/DataDownload.py, utils/test/TestRunner.py, utils/test/UnitTestUtilities.py, utils/test/capability_tests/AllCapabilityTestSuite.py, utils/test/capability_tests/ERGToolsTestSuite.py, utils/test/capability_tests/HelicopterLandingZoneToolsTestSuite.py, utils/test/visibility_tests/AllVisibilityTestSuite.py, utils/test/visibility_tests/SunPositionAnalysisToolsTestSuite.py, utils/test/visibility_tests/SunPositionAndHillshadeTestCase.py
Created and used Configuration.Logger variable. Also moved file path variables out of Configuration and into SunPositionAndHillshadeTestCase.
=> Configuration.Logger and Sun Position paths

data_management/toolboxes/mdcs/scripts/AddRasters/AddRasters.py, data_management/toolboxes/mdcs/scripts/Base/Base.py, data_management/toolboxes/mdcs/scripts/CreateMD/CreateMD.py, data_management/toolboxes/mdcs/scripts/MDCS.py, data_management/toolboxes/mdcs/scripts/SetMDProperties/SetMDProperties.py, data_management/toolboxes/mdcs/scripts/SolutionsLog/logger.py, data_management/toolboxes/mdcs/scripts/solutionsLib.py
=> Updates for MDCS from mdcs-py

utils/test/visibility_tests/RangeRingUtilsTestCase.py
Was asked to do this change outside of the other PR review - https://github.com/Esri/solutions-geoprocessing-toolbox/pull/434#issuecomment-218741671
=> Simplify import logic

utils/test/capability_tests/ERGScriptTestCase.py, utils/test/capability_tests/HLZTouchdownPointsTestCase.py
This change should trap when the *test* fails as well as the tool being tested.
* Capabilty/HLZ tests
* Capability/ERG tests
More to come...
=> Working to swap test cases from 3 methods to 2 methods.

data_management/toolboxes/scripts/PolylineToPolygon.py
Optimize arcpy polyline to polygon conversion
See: issue #386 
Changed to copy/use the same method in [military-tools-geoprocessing-toolbox](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/toolboxes/scripts/ConversionUtilities.py#L66-#L169)
See: issue #386 
Tested TableToEllipse tool in ArcMap 10.4.1 with the output from the test data generator script in #386 
**Note**: Could **not test in Pro** because the TableToEllipse model seems to be failing in Pro 1.4 before it gets to this step ( @mfunk could you test this model to see if it works for you?)
=> Issue #386 - Optimize PolylineToPolygon

CONTRIBUTING.md, utils/test/WritingTests.md
Mostly Issues closed in Milestone 5.
* minor doc changes to MD files
* Issues closed: https://github.com/Esri/solutions-geoprocessing-toolbox/milestone/6
Issues closed are listed here: https://github.com/Esri/solutions-geoprocessing-toolbox/milestone/6
Scheduled release.
Manual verification of doc fixes.
=> Merge DEV to MASTER for JUNE2017 release

README.md
#470 + removed tags line
Note: someone with Admin rights should add the repo tags/topics [back to the repo](https://github.com/blog/2309-introducing-topics)
=> Issue #470 - Readme link

.gitignore, utils/test/.gitignore, utils/test/Configuration.py, utils/test/DataDownload.py, utils/test/TestRunner.py, utils/test/UnitTestUtilities.py, utils/test/incident_analysis_tests/ClusterAnalysisTestCase.py, utils/test/incident_analysis_tests/CountIncidentsByLOCTestCase.py, utils/test/incident_analysis_tests/FindPercentChangeTestCase.py, utils/test/incident_analysis_tests/HotSpotsByAreaTestCase.py, utils/test/incident_analysis_tests/IncidentAnalysisToolsTestSuite.py, utils/test/incident_analysis_tests/IncidentDensityTestCase.py, utils/test/incident_analysis_tests/IncidentHotSpotsTestCase.py, utils/test/sun_position_analysis_tests/SunPositionAnalysisToolsTestSuite.py, utils/test/sun_position_analysis_tests/SunPositionAndHillshadeTestCase.py, utils/test/test_data/Readme.md
Refactor/reorg test suite a bit to 
1. Fix paths based on new folder (re)names
2. Remove Pro & ArcMap specific methods
3. Allow test cases to be run standalone (add unittest.main )
4. Move test data location to /test_data folder  
#520 
Fix paths, eliminate redundancy, make tests easier to add in future and run stand-alone
Unit test runner - IMPORTANT NOTE: 4 / 7 tests are still failing unrelated to these changes (see: https://github.com/Esri/solutions-geoprocessing-toolbox/issues?q=is%3Aopen+is%3Aissue+label%3A%22unit+test%22 )
=> Update/fix unit tests after repo reorg - #520

utils/test/Configuration.py, utils/test/TestRunner.py, utils/test/geonames_tests/GeoNamesTestCase.py, utils/test/geonames_tests/GeoNamesToolsTestSuite.py
Add Geonames Tests - #533 
#533
UnitTest
=> Add Geonames Tests

clearing_operations/layers/GRG.lyrx, clearing_operations/layers/NumberedStructures.lyrx
No changes to anything else in the repo, just the initial upload of lyrx files
=> Initial upload of lyrx files used in the pro template

CONTRIBUTING.md
@csmoore Is this better?
Clarification of *tooldata* folder contents should NOT contain sample/example/test data.
N/A
Clarification of *tooldata* folder contents should NOT contain sample/example/test data.
Ask a friend.
=> Clarification of *tooldata* folder contents

military_features/scripts/AppendMilitaryFeatures.py, military_features/scripts/CalcRepRuleField.py, military_features/scripts/CalcSIDCField.py, military_features/scripts/GeometryConverter.py, military_features/scripts/MilitaryUtilities.py, military_features/scripts/SymbolDictionary.py, military_features/scripts/WriteFeatureFromMessage.py, military_features/scripts/WriteMessageFromFeature.py
Remaining code cleanup from #597
=> Remaining code cleanup from #597

clearing_operations/scripts/NumberFeaturesTool.py, utils/test/clearing_operations_tests/ClearingOperationsNumberFeaturesTestCase.py
See #607
See #607
Unit Tests (also updated these to add test case for #607)
=> Set output to None if no output param given #607

clearing_operations/scripts/RefGrid.py
I am not sure why ArcGIS Pro in seeing the variable interval as a float
when desktop doesn't, where the tool runs fine. To solve the issue I have
cast the variable to an integer to ensure it is being seen as an int in both the range
steps on line 430 & 431
Within this PR there is also a fix for #619, again down to how Pro is handling numbers (float vs int)
Also fixed #614 & #617
#615 
#619
#614
#617
Fixes a bug in Pro where the tool will fail
Manually tested in ArcGIS Pro 2.0 and ArcMap 10.4.1
=> Address issue #615

utils/test/TestRunner.py
=> Partially Addresses #632

utils/test/clearing_operations_tests/ClearingOperationsCreateGRGFromAreaTestCase.py, utils/test/clearing_operations_tests/ClearingOperationsCreateGRGFromPointTestCase.py, utils/test/clearing_operations_tests/CreateReferenceSystemGRGFromAreaTestCase.py
Update tests after parameter changes in #591 / https://github.com/Esri/solutions-geoprocessing-toolbox/commit/e2ddfa9704d0ec2f41d790abe39ea013fb13c159 / See also https://github.com/Esri/solutions-geoprocessing-toolbox/issues/634#issuecomment-353651227
=> Update tests to latest parameter list

utils/test/ClearingOperationsTestKickDesktop.bat, utils/test/ClearingOperationsTestRunner.py, utils/test/MilitaryFeaturesTestKickDesktop.bat, utils/test/MilitaryFeaturesTestRunner.py
Added Military Features and Clearing Operations Test runner by commenting out the other solutions from the main test runner.
Until further notice we will use the main test runner script as a starting point and comment out the solutions that do not need to run on the single test runner file. This will allow us to build a solution by just calling one test. This was done with this approach to lower the LOE and move forward. An issue has been logged: 
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/647
=> Adding single test runners

clearing_operations/scripts/RefGrid.py
Removed the need for the temp scratch database my creating all temp layers in_memory.
=> Address Issue #624

clearing_operations/scripts/GRGUtilities.py
=> Address issue #585

clearing_operations/scripts/GRGUtilities.py
Address issue #646 
Added a check to see if input feature class contains any features.
If empty Error is raised,
If more than 1, warning message generated to state last feature used
=> Address issue #646

clearing_operations/scripts/RefGrid.py
Address issue #625 
Added check to see if the input AOI overlaps either of the polar
regions. If true message added to the console informing the user that
cells within the polar region will not be created
=> Address issue #625

clearing_operations/scripts/GRGUtilities.py
The script was reusing a rotate feature class function that was generic
so that it could be used against any feature class. As part of this it
used the arcpy.AddJoin_management to map over the existing feature class
attributes. This process seemed to cause an issue in Pro.
As we know that there is only one attrribute field to map over (Grid) I
have change script to do this in the search cursor and removed the join.
=> Address issue #657

clearing_operations/scripts/GRGUtilities.py
Updated the create fishnet tool input parameters to address issue #660
=> Address issue #660

README.md
Clearing operations was still referring to a toolbox for ArcMap and Pro, this toolbox has been refactored as a python toolbox that will work across both applications.
=> Update Readme to reflect current toolboxes
